# MCSV.KR 플랫폼을 이용해 주셔서 감사합니다.
# 이 설정파일은 MCSV.KR 클라이언트가 정상적으로 작동하기 위한 설정을 포함하고 있습니다.

# MCSV.KR 클라이언트가 설정파일의 버전을 관리하기 위해 사용합니다.
# 버그 수정 목적이 아니라면, 수정하지 마시기 바랍니다.
version: 1

# MCSV.KR 클라이언트가 서버에 접속하기 위한 정보를 저장합니다.
credentials:

  # 이 서버의 고유 ID 를 정의합니다.
  # 만약 없다면, /mcsv setup 명령을 통해 마법사를 실행해 주세요.
  serverId: null

  # api.mcsv.kr와 통신하기 위한, 액세스 토큰을 정의합니다.
  # 이 정보는 절대 타인에게 노출해서는 안 됩니다.
  # 만약 값이 null 이라면, /mcsv login 명령을 통해 로그인을 진행해 주세요.
  accessToken: null

  # api.mcsv.kr와 통신하기 위한, 리프레시 토큰을 정의합니다.
  # 이 정보는 절대 타인에게 노출해서는 안 됩니다.
  # 만약 값이 null 이라면, /mcsv login 명령을 통해 로그인을 진행해 주세요.
  refreshToken: null
