# Minehub 플랫폼을 이용해 주셔서 감사합니다.
# 이 설정파일은 Minehub ServerAgent가 정상적으로 작동하기 위한 설정을 포함하고 있습니다.

# Minehub ServerAgent가 설정파일의 버전을 관리하기 위해 사용합니다.
# 버그 수정 목적이 아니라면, 수정하지 마시기 바랍니다.
version: 1

server:
  id: ""
