# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    paths:
      - "src/**/*.java"
      - "pom.xml"
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**/*.java"
      - "pom.xml"
      - ".github/workflows/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [1.8, 1.12, 1.15]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.python-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.python-version }}
      - name: Setup Spigot Build Environment
        run: |
          mkdir BuildTools
          cd BuildTools
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev latest
          cd ..
      - name: Build with Maven
        run: mvn
