# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release

on:
  push:
    branches: [ main ]
    paths:
      - "src/**/*.java"
      - "pom.xml"
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**/*.java"
      - "pom.xml"
      - ".github/workflows/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Setup Spigot Build Environment
        run: |
          mkdir BuildTools
          cd BuildTools
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev latest
          cd ..
      - name: Update version of maven file to ${{ github.event.release.tag_name }}
        run: mvn versions:set -DnewVersion=${VER_TAG:1}
        env:
          VER_TAG: ${{ github.event.release.tag_name }}
      - name: Build with Maven
        run: mvn package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Client.jar
          # A file, directory or wildcard pattern that describes what to upload
          path: target/**/*.jar
